### PR TITLE
Add E2E testing & fix #57, #58 and #60

### LINKED ISSUE #57: Problem with Video Name outputs
image
As you can see in this image, the basic function no longer works.  I have tried several different playlists and I get this same error.

### PR DESCRIPTION
**Pull request by trustedtomato**

### CODE REVIEW

**Comment by trustedtomato** [comment]
As I see, both #59 and #55 do a similar thing, but directly testing the ytpl function is unique to this PR and would be useful, I think.

**Comment by trustedtomato** [comment]
Added x-youtube-client-* headers as Aasim did in #55. Cleaned up the code a bit, now Codecov is happy too.

**Comment by trustedtomato** [comment]
#64 makes the change in lib/main.js obsolete, the E2E testing might still be useful though.

**Comment by TimeForANinja** [comment]
> #64 makes the change in lib/main.js obsolete, the E2E testing might still be useful though.

i do agree and would be happy to still implement the e2e tests
you want to adjust the PR?

**Comment by trustedtomato** [comment]
Yesss looks like I've managed to do it, this git thing is tricky, even after several years of usage.

**Comment by TimeForANinja** [comment]
👍  thanks, appreciate it

**Pull request merged**
