### PR TITLE
[Possible Fix] TypeError: Cannot read property '1' of null

### PR DESCRIPTION
**Pull request by N5E713**
Possible solution to issues #57 and #58.

### CODE REVIEW

**Comment by Roki100** [comment]
doesnt work for me, it brings back the {"reload": "now"} body however #55 seems to also fix the `TypeError: Cannot read property '1' of null` issue

**Comment by N5E713** [comment]
I found a better solution by just removing bingbot from the user agent. It seems that YouTube maybe verifying authenticity of named user agents

**Comment by naugtur** [comment]
I tried it with the useragent change and it works for me.

**Comment by naugtur** [comment]
I saved both response bodies to a file and the diff is veeery long.

**Comment by TimeForANinja** [comment]
should be fixed with #64

**Pull request closed without merging**
