### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by trustedtomato**
Issue: #2 
I couldn't wait for the answer, so I did added them.
Also, if you accept, would you do a `npm publish` please?

### CODE REVIEW

**Comment by TimeForANinja** [comment]
Thanks for the PR and sorry for my late PR.
I don't see the sense of the node_modules folder and the yarn.lock file in this PR thou...

**Comment by trustedtomato** [comment]
Ooops, that's a mistake

**Comment by trustedtomato** [comment]
I removed those and added "node_modules" to .gitignore because it should be there. Its non-existence caused the accident.

**Comment by TimeForANinja** [comment]
Thanks again, will try to keep them up to date ^^

**Pull request merged**
