### PR TITLE
I made the code compatible with the latest data return

### PR DESCRIPTION
**Pull request by dbrn**
Some things still need to be tested throughout. But it works for my app and I think this could be a good starting point to make the library work again.

### CODE REVIEW

**Comment by dbrn** [comment]
I see there are some problems with the linter, could someone please fix them?

**Comment by mirsella** [comment]
thanks for helping them fix it.

for me it isn't working :
```
const ytpl = require('ytpl')
ytpl("playlist_url")
  .then(playlist => console.log(playlist))
```
i got 2 different error with 2 differents playlists.

with this playlist : https://www.youtube.com/playlist?list=PL2788304DC59DBEB4
I'm getting :
```
/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/util.js:104
  const scriptBodyObject = JSON.parse(scriptBody);
                                ^

SyntaxError: Unexpected token ; in JSON at position 155360
    at JSON.parse (<anonymous>)
    at getDataObject (/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/util.js:104:33)
    at Object.exports.getGeneralInfo (/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/util.js:26:22)
    at module.exports (/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/firstpage.js:29:25)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async module.exports (/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/main.js:13:20)
```

and with this playlist : https://www.youtube.com/playlist?list=PLnYA0n5BTNscRlnFBkNGJrCyKdOqGtID9
I'm getting :
```
/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/util.js:96
  string.replace(/\n\r?/g, ' ')
         ^

TypeError: Cannot read property 'replace' of undefined
    at exports.removeHtml (/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/util.js:96:10)
    at Object.exports.getGeneralInfo (/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/util.js:42:18)
    at module.exports (/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/firstpage.js:29:25)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async module.exports (/home/mirsella/Downloads/ytpl/node_modules/ytpl/lib/main.js:13:20)
```

thanks you. have a goodnight

**Comment by dbrn** [comment]
Thank you for your feedback and patience, @mirsella!
I fixed those two bugs, and now it seems to work fine.
Check the latest commit!

**Comment by mirsella** [comment]
work for me :+1:

**Comment by DeaLoux** [comment]
Thank you for your fix

Unfortunately I'm getting an error
```TypeError: Cannot read property 'simpleText' of undefined
    at Object.exports.buildVideoObject (P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\util.js:100:62)
    at P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\firstpage.js:33:23
    at Array.map (<anonymous>)
    at module.exports (P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\firstpage.js:33:6)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\main.js:13:20)
    at async PlayCommand.run (P:\Software Projects\Discord Bot\Aqukin\src\opus\commands\play.js:50:13)
``` 
I think it has something to do with obtaining the playlist/track duration, thank you.

**Comment by dbrn** [comment]
Can I see the error message, please?

**Comment by DeaLoux** [comment]
I tried it again with different playlists and the error seems to occur only when there're private/removed videos in the playlist. If not then it seems to be working fine, thank you.

**Comment by dbrn** [comment]
> I tried it again with different playlists and the error seems to occur only when there're private/removed videos in the playlist. If not then it seems to be working fine, thank you.

If you still have the log of the previous error, please send it over :) I'd love to give it a look!

**Comment by DeaLoux** [comment]
> > I tried it again with different playlists and the error seems to occur only when there're private/removed videos in the playlist. If not then it seems to be working fine, thank you.
> 
> If you still have the log of the previous error, please send it over :) I'd love to give it a look!

I'm testing it with my bot using this function
```
ytpl(query, { limit: Infinity }).then(async playlist =>{
   console.log(playlist);
   // do something
}).catch((err) => {
    console.log(err);
    // do something 
)});
```

I'm getting the error while trying with this playlist, or any playlist with at least one private/removed videos actually: https://www.youtube.com/playlistlist=PLpt61bADOMwXIZpLr09sCNeocN7CXjcoS

The only thing that it logged is the error `TypeError: Cannot read property 'simpleText' of undefined` at `ytpl\lib\util.js:100:62` 
```
TypeError: Cannot read property 'simpleText' of undefined
    at Object.exports.buildVideoObject (P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\util.js:100:62)
    at P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\firstpage.js:33:23
    at Array.map (<anonymous>)
    at module.exports (P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\firstpage.js:33:6)
```

This playlist is working without the error: https://www.youtube.com/watch?v=SlPhMPnQ58k&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10

Thank you

**Comment by dbrn** [comment]
@DeaLoux it should be fine now :)

**Comment by DeaLoux** [comment]
Thank you @dbrn for your fix, I tested it with the mentioned function and there's still an error with any playlist with more than 100 videos, aka requires the 2nd page. Playlists with less than 100 videos or within the 1st page are working correctly. 

From what I know the Youtube returns the playlist in pages at 100 videos each, hence I think it has to do with the way the playlist pages are obtained rather than your fix being the problem.

It's working correctly these two playlists
https://www.youtube.com/playlist?list=PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU (Exactly 100 videos)
https://www.youtube.com/playlist?list=PLpt61bADOMwXIZpLr09sCNeocN7CXjcoS (35 videos including 2 private ones)

These two playlist result in the error `TypeError: Cannot read property 'shortBylineText' of undefined`
https://www.youtube.com/playlist?list=PLx0sYbCqOb8QTF1DCJVfQrtWknZFzuoAE (101 videos including 1 private)
https://www.youtube.com/playlist?list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10 (240 videos)

```
TypeError: Cannot read property 'shortBylineText' of undefined
    at Object.exports.buildVideoObject (P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\util.js:95:46)
    at P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\firstpage.js:33:23
    at Array.map (<anonymous>)
    at module.exports (P:\Software Projects\Discord Bot\Aqukin\node_modules\ytpl\lib\firstpage.js:33:6)
```

I really appreciate for your efforts 👍

**Review by iSamuelCO — APPROVED** [review]

**Comment by dbrn** [comment]
Thank you @DeaLoux!
I'm trying to deliver something that could make this library work again... And without your feedback, I wouldn't be able to do it :)
Let me see what I can do for what you've just told me.

**Comment by dbrn** [comment]
Now the lib shouldn't crash anymore.
Hopefully, it works with longer lists as well. Here it seems to work fine.

**Comment by DeaLoux** [comment]
Thank you @dbrn, it works for me now.
I'm glad that I can help, I'll be sure to let you know if there's any problem left. Please have a good day/night 👍

**Comment by TimeForANinja** [comment]
added another wip-branch and changed the merge target
i'll have a look later today and most likely merge it as a starting point
so thanks for the work already 👍

**Comment by dbrn** [comment]
> added another wip-branch and changed the merge target
> i'll have a look later today and most likely merge it as a starting point
> so thanks for the work already 👍 
> 
> Edit: the linter failing is no problem since tests will crash anyway

Thank you.
I'm here if you need further help.

**Comment by TimeForANinja** [comment]
😉 watch out with using linters
after fixing the eslint run it wasn't happy

**Comment by dbrn** [comment]
Thank you 😅

**Pull request merged**
